# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RTFMD.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mw1(object):
    def setupUi(self, mw1):
        mw1.setObjectName("mw1")
        mw1.setEnabled(True)
        mw1.resize(718, 533)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("1.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("1.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        mw1.setWindowIcon(icon)
        mw1.setAutoFillBackground(False)
        mw1.setStyleSheet("background-color: rgb(153, 76, 0);\n"
"background-color: rgb(85, 85, 127);")
        mw1.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(mw1)
        self.centralwidget.setObjectName("centralwidget")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(50, 260, 141, 41))
        self.b1.setAutoFillBackground(False)
        self.b1.setStyleSheet("background-color: rgb(255, 170, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b1.setIcon(icon1)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(50, 320, 141, 41))
        self.b2.setAutoFillBackground(False)
        self.b2.setStyleSheet("background-color: rgb(255, 170, 0);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b2.setIcon(icon2)
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(50, 380, 141, 41))
        self.b3.setAutoFillBackground(False)
        self.b3.setStyleSheet("background-color: rgb(255, 170, 0);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("webcam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b3.setIcon(icon3)
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QPushButton(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(50, 440, 141, 41))
        self.b4.setMinimumSize(QtCore.QSize(141, 0))
        self.b4.setAutoFillBackground(False)
        self.b4.setStyleSheet("background-color: rgb(255, 170, 0);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b4.setIcon(icon4)
        self.b4.setObjectName("b4")
        self.f1 = QtWidgets.QFrame(self.centralwidget)
        self.f1.setGeometry(QtCore.QRect(230, 170, 451, 311))
        self.f1.setAutoFillBackground(False)
        self.f1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.f1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.f1.setLineWidth(15)
        self.f1.setMidLineWidth(15)
        self.f1.setObjectName("f1")
        self.tb1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb1.setGeometry(QtCore.QRect(20, 10, 691, 71))
        self.tb1.setAutoFillBackground(True)
        self.tb1.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"background-color: rgb(212, 212, 212);")
        self.tb1.setObjectName("tb1")
        self.tb2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb2.setGeometry(QtCore.QRect(120, 80, 471, 51))
        self.tb2.setAutoFillBackground(True)
        self.tb2.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"background-color: rgb(172, 172, 172);")
        self.tb2.setObjectName("tb2")
        mw1.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mw1)
        self.statusbar.setObjectName("statusbar")
        mw1.setStatusBar(self.statusbar)

        self.retranslateUi(mw1)
        QtCore.QMetaObject.connectSlotsByName(mw1)
        

    # x = input("Press Key To Perform Funtionallity")
    # mw1 = x
       
    def retranslateUi(self, mw1):
        x = input("Press Key To Perform Funtionallity")
        _translate = QtCore.QCoreApplication.translate
        mw1.setWindowTitle(_translate("mw1", "Real-Time-Face-Mask-Detection"))
        self.b1.setText(_translate("mw1", "Upload Image"))
        self.b2.setText(_translate("mw1", "Predict Image Result"))
        self.b3.setText(_translate("mw1", "Open Webcam"))
        self.b4.setText(_translate("mw1", "Close Detector"))
        self.tb1.setHtml(_translate("mw1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600; text-decoration: underline; color:#ffffff;\">Real Time Face Mask Detection</span></p></body></html>"))
        self.tb2.setHtml(_translate("mw1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">FYP</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; text-decoration: underline; color:#ffffff;\">Federal Urdu University Of Arts, Science and Technology</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mw1 = QtWidgets.QMainWindow()
    ui = Ui_mw1()
    ui.setupUi(mw1)
    mw1.show()
    sys.exit(app.exec_())
